import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const MARKER = "Generated by planalot install cc";

export interface InstallCcOptions {
  cliPath: string;
  force?: boolean;
}

export interface InstallCcResult {
  commandPath: string;
}

export async function installCcExtension(options: InstallCcOptions): Promise<InstallCcResult> {
  const commandPath = join(homedir(), ".claude", "commands", "planalot.md");
  await writeGeneratedFile(commandPath, buildPlanalotCommand(options.cliPath), options.force === true);
  return { commandPath };
}

async function writeGeneratedFile(path: string, content: string, force: boolean): Promise<void> {
  if (existsSync(path) && !force) {
    const current = readFileSync(path, "utf8");
    if (!current.includes(MARKER)) {
      throw new Error(`Refusing to overwrite non-planalot file at ${path}. Re-run with --force if this is intentional.`);
    }
  }

  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFile(path, content, "utf8");
}

function buildPlanalotCommand(cliPath: string): string {
  const command = shellCommandForCli(cliPath);
  return `---
description: Open an existing markdown plan in Planalot, or create a plan first from a planning request
allowed-tools: Bash(${command}:*), Read, Write, Edit
---

<!-- ${MARKER}. Re-run \`planalot install cc\` after updating or moving planalot. -->

# Planalot planning session

User request / arguments:

\`\`\`text
$ARGUMENTS
\`\`\`

## Contract

Planalot never creates plan files. It only opens and watches an existing \`.md\` or \`.mdx\` file.

## If the argument is an existing markdown plan path

1. Verify the file exists and is inside the current workspace.
2. Run:

   \`\`\`bash
   ${command} "<path>"
   \`\`\`

3. Tell the user Planalot is open. Do not rewrite the plan unless the user asks.

## If the argument is natural language, missing, or not a markdown path

1. Create or update a useful markdown plan file in the current workspace first. Prefer a clear filename such as \`PLAN.md\`, \`TASK_PLAN.md\`, or a specific \`*_PLAN.md\`.
2. The plan must contain enough detail for review: goal, context, proposed approach, implementation slices, verification, risks/open questions.
3. After the file exists, run:

   \`\`\`bash
   ${command} "<created-plan-file.md>"
   \`\`\`

4. Tell the user which file was created/opened.

## If the argument looks like a markdown path but does not exist

Do not run Planalot. Tell the user the file must exist first, or create the file if the user's request clearly asks to start a new plan.
`;
}

function shellCommandForCli(cliPath: string): string {
  const node = quoteForShell(process.execPath);
  const cli = quoteForShell(cliPath);
  return `${node} ${cli}`;
}

function quoteForShell(value: string): string {
  if (/^[A-Za-z0-9_./:=-]+$/.test(value)) return value;
  return `"${value.replace(/"/g, '\\"')}"`;
}
