import { homedir } from "node:os";
import { join } from "node:path";
import {
  computeInSync,
  convergeRemove,
  convergeWrite,
  shellCommandForCli,
  type ConvergeReport,
  type ConvergeStep,
} from "@planalot/extension-kit";

const MARKER = "Generated by planalot install cc";
const SKILL_NAME = "planalot";
const SKILL_REVISION = "wake-on-feedback-v1";

export interface ConvergeCcOptions {
  cliPath: string;
  version: string;
}

function ccPaths(): { skillPath: string; commandPath: string } {
  return {
    skillPath: join(homedir(), ".claude", "skills", SKILL_NAME, "SKILL.md"),
    commandPath: join(homedir(), ".claude", "commands", `${SKILL_NAME}.md`),
  };
}

/**
 * Converge the Claude Code resources planalot owns:
 *   - skills/planalot/SKILL.md → authoritative (re)write
 *   - commands/planalot.md     → remove iff it's ours (we no longer install a
 *                                legacy command; a user's own /planalot is kept)
 */
async function converge(options: ConvergeCcOptions, apply: boolean): Promise<ConvergeReport> {
  const { skillPath, commandPath } = ccPaths();
  const steps: ConvergeStep[] = [];

  steps.push({
    path: skillPath,
    action: await convergeWrite(skillPath, buildPlanalotSkill(options.cliPath, options.version), apply),
  });

  const commandAction = await convergeRemove(commandPath, MARKER, apply);
  steps.push({
    path: commandPath,
    action: commandAction,
    ...(commandAction === "left-foreign" ? { note: "not planalot-generated — left as is" } : {}),
  });

  return {
    harness: "cc",
    mode: apply ? "apply" : "check",
    version: options.version,
    steps,
    drift: [],
    inSync: computeInSync(steps),
  };
}

export function installCcExtension(options: ConvergeCcOptions): Promise<ConvergeReport> {
  return converge(options, true);
}

export function checkCcExtension(options: ConvergeCcOptions): Promise<ConvergeReport> {
  return converge(options, false);
}

function buildPlanalotSkill(cliPath: string, version: string): string {
  const command = shellCommandForCli(cliPath);
  return `---
name: planalot
description: Use when the user asks to create, continue, review, or implement a Planalot plan workspace from Claude Code.
planalot_version: ${version}
planalot_skill_revision: ${SKILL_REVISION}
---

# Planalot

${MARKER}. Re-run \`planalot install cc\` after updating or moving Planalot.

Installed Planalot version: \`${version}\`.

User request / arguments:

\`\`\`
$ARGUMENTS
\`\`\`

## Purpose

Planalot is a local second-brain planning workspace. It stores durable plans under \`~/.planalot/plans/<id>\`, with \`manifest.json\`, \`feedback.json\`, and plan-authored files under \`requirements/\`, \`design/\`, and \`tasks/\`. Use the CLI as the tool-like interface from Claude Code.

## Current Claude Code Harness Boundary

This integration is intentionally non-MCP. Claude Code interacts with Planalot by running CLI commands. To receive browser feedback live you must **attach as a harness** and keep that process running in the background — otherwise the browser shows "No harness connected" and every feedback send fails.

## Workflow — route on the request, then drive ONE plan

First decide intent from the arguments and conversation:

- The argument is a markdown file path (e.g. \`PLAN.md\`) → **import** it.
- The user said "continue/resume <name>" → **find** then **read**.
- Otherwise → **create** a new plan and author its requirements.

### 1. Create / import / continue

\`\`\`powershell
# new plan
${command} create --name "Plan Name" --json
# from an existing file (Planalot copies it and owns it after)
${command} import "PLAN.md" --name "Plan Name" --json
# continue: find one match, then read everything before changing anything
${command} find "payments" --status planning --json
${command} read <planId> --all --json
\`\`\`

Note the returned \`planId\`; every later command uses it.

### 2. Attach as the harness — REQUIRED, run in the BACKGROUND with \`--exit-on-feedback\`

Launch this as a background task (run the Bash command with \`run_in_background: true\`):

\`\`\`powershell
${command} attach <planId> --type claude-code --drive --exit-on-feedback
\`\`\`

This registers you with Planalot (the browser shows you connected and driving) and keeps you present via heartbeat. **\`--exit-on-feedback\` is what makes you react to the browser.** The command suppresses presence noise and **exits the instant the user sends something you must act on** — a feedback/review round, an answer to a question you asked, or a Build/Accept. It stays registered when it exits (no detach), so your presence does not drop.

Why the flag matters: Claude Code only re-invokes you when a background task **exits**, never for mid-stream output. A plain \`attach\` loop never exits, so an idle session never notices browser feedback. With \`--exit-on-feedback\`, the task's exit IS your wake-up — its final output line is the event to handle. **Always use the flag.**

Planalot gives this instance a stable friendly name (e.g. \`amber-otter\`) shown in the browser's harness list and "Send to" dropdown, and reuses it for this working directory across plans and reconnects. To choose your own name, add \`--name "<name>"\`.

The first printed line is \`{"type":"attached","name":"…"}\` — note that name. When the background task later **completes**, that is your signal to run step 4.

### 3. Author the plan, then open the browser

As the driver you hold the plan's edit lease. Write layered files via stdin — on PowerShell use \`-Raw\` and UTF-8 to avoid mangling content:

\`\`\`powershell
Get-Content -Raw updated-index.md | ${command} write <planId> requirements/index.md --stdin --json
${command} open <planId>
\`\`\`

Resolve top-down: \`requirements/\` → \`design/\` → \`tasks/\`.

### 4. React when the background attach task exits

When the background \`attach --exit-on-feedback\` task **completes**, you were woken because there is something to act on. Every time, in this order:

1. **Relaunch the waiter immediately** — start the same \`${command} attach <planId> --type claude-code --drive --exit-on-feedback\` again with \`run_in_background: true\`, FIRST, before the work below. This keeps you present and holding the edit lease while you work, and re-arms the wake-up for the next event. (The relaunch resumes cleanly: anything that arrived in the brief gap is replayed.)
2. **Read authoritative state — do not trust only the printed line:**
   - \`${command} feedback <planId> --open --json\` → the open feedback/review round(s), each with its request markdown.
   - \`${command} read <planId> --all --json\` → current file contents if you need them.
3. **Apply changes and respond in one \`feedback-result\` call.** Put each new file's full text in \`fileChanges[].content\`; the daemon writes the files and releases the edit lease as part of the result, so you do not need separate \`write\` calls during the round:

\`\`\`powershell
Get-Content -Raw feedback-result.json | ${command} feedback-result <planId> --stdin --json
\`\`\`

If the wake had no open feedback, it was a Build/Accept (\`plan.build\` / \`plan.accepted\` / \`implementation.requested\`) — act on that instead (e.g. begin implementation).

### 5. Finish

\`\`\`powershell
# hand off for implementation once feedback is resolved
${command} implement <planId> --json
# when fully done with the plan, stop the background attach and deregister
${command} detach <planId>
\`\`\`

## Research sessions

A research session is a plan-scoped, single-file investigation that runs alongside the plan: a markdown \`scope\` plus a list of \`inquiries\` (questions to resolve). Inquiries are individually addressable and **lease-exempt** — many subagents can resolve them in parallel even while a plan feedback round holds the edit lease. Reach for this when a task means "investigate or enumerate N things without missing any."

\`\`\`powershell
# create a session (scope via stdin)
"What to investigate" | ${command} research-new <planId> --title "Auth model" --scope-stdin --json
# bulk-add inquiries from a JSON array — enumerate deterministically, then add all at once
'[{"title":"map providers"},{"title":"token lifecycle"}]' | ${command} research-add <planId> <researchId> --stdin --json
${command} research-list <planId> --json
${command} research-show <planId> <researchId> --json
# resolve one inquiry (atomic; safe to run concurrently for different inquiries)
"findings" | ${command} research-update <planId> <researchId> <inquiryId> --status resolved --result-stdin --json
\`\`\`

Drive it like a work queue:

1. Enumerate the work **deterministically** (e.g. glob the files), then bulk-create one inquiry each. The count is a fact: N items in -> N inquiries.
2. Spawn one subagent per \`open\` inquiry. Each marks its inquiry \`active\` (optionally \`--assignee\`), does the work, then \`research-update … --status resolved --result-stdin\` with its findings.
3. Loop until no inquiry is \`open\` or \`active\`. Termination is by count off the store, not the model's memory — that is the completeness guarantee.

The browser shows research in the left rail (under Files) with live per-inquiry status. Inquiry writes are lease-exempt, so you do not need to hold the plan edit lease to update them.

## Layered Plan Contract

Resolve top-down: \`requirements/\` -> \`design/\` -> \`tasks/\`.

- \`requirements/\`: goals, business rules, constraints, acceptance criteria, non-goals, open questions.
- \`design/\`: architecture, UX flows, data model, APIs, tradeoffs, risks, rejected alternatives.
- \`tasks/\`: implementation slices, dependencies, file ownership, verification commands, rollout notes.

If requirements change, reconcile design/tasks. If design changes, reconcile tasks. Do not silently change requirements because of downstream feedback; ask a question or explain the conflict.

## Feedback Result Protocol

Planalot sends feedback requests as markdown and expects only valid JSON back through \`feedback-result\`.

The result shape is:

\`\`\`json
{
  "schemaVersion": 1,
  "feedbackSessionId": "fs_...",
  "fileChanges": [
    {
      "path": "requirements/index.md",
      "operation": "updated",
      "feedbackItemIds": ["fb_..."],
      "content": "optional full file content",
      "alreadyApplied": false
    }
  ],
  "responses": [
    {
      "id": "r_...",
      "kind": "question",
      "feedbackItemIds": ["fb_..."],
      "layer": "requirements",
      "text": "Question, clarification, or insight.",
      "expectsUserFollowUp": true,
      "suggestedAnswers": []
    }
  ]
}
\`\`\`

## Constraints

- Planalot owns the source of truth once a plan is created or imported.
- Plan-authored files must be under \`requirements/\`, \`design/\`, or \`tasks/\`.
- \`requirements/index.md\` is required and canonical.
- Default discovery excludes expired plans; use \`--include-expired\` only when the user asks for old plans.
- Do not treat feedback as known until a background \`attach --exit-on-feedback\` task wakes you (then confirm with \`feedback <planId> --open --json\`) or it appears in chat.
- Always keep exactly one background \`attach --exit-on-feedback\` task armed: relaunch it right after each wake, and \`detach\` only when you are finished with the plan. With no waiter running you appear connected only until the heartbeat lapses, then the browser shows "No harness connected" and you stop reacting to feedback.
- A feedback round is addressed to one harness, which holds an exclusive edit lease — the daemon rejects plan writes from anyone else with HTTP 409. Respond with \`feedback-result\` to release it.
`;
}

