import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const MARKER = "Generated by planalot install cc";
const SKILL_NAME = "planalot";
const SKILL_REVISION = "harness-attach-v3";

export interface InstallCcOptions {
  cliPath: string;
  version: string;
  force?: boolean;
}

export interface InstallCcResult {
  skillPath: string;
  commandPath: string;
  legacyCommandUpdated: boolean;
}

export interface CheckCcOptions {
  version: string;
}

export interface CheckCcResult {
  localVersion: string;
  skillPath: string;
  commandPath: string;
  skill: CcVersionProbe;
  legacyCommand: CcVersionProbe;
  inSync: boolean;
  problems: string[];
}

export interface CcVersionProbe {
  path: string;
  exists: boolean;
  generated: boolean;
  skillVersion?: string;
  skillRevision?: string;
  matches: boolean;
}

export async function installCcExtension(options: InstallCcOptions): Promise<InstallCcResult> {
  const skillPath = join(homedir(), ".claude", "skills", SKILL_NAME, "SKILL.md");
  const commandPath = join(homedir(), ".claude", "commands", `${SKILL_NAME}.md`);

  await writeGeneratedFile(skillPath, buildPlanalotSkill(options.cliPath, options.version), options.force === true);

  const legacyCommandUpdated = await maybeWriteLegacyCommand(commandPath, options);
  return { skillPath, commandPath, legacyCommandUpdated };
}

export function checkCcExtension(options: CheckCcOptions): CheckCcResult {
  const skillPath = join(homedir(), ".claude", "skills", SKILL_NAME, "SKILL.md");
  const commandPath = join(homedir(), ".claude", "commands", `${SKILL_NAME}.md`);
  const skill = readVersionProbe(skillPath, options.version);
  const legacyCommand = readVersionProbe(commandPath, options.version);
  const problems: string[] = [];

  if (!skill.exists) {
    problems.push(`Claude Code skill is missing: ${skillPath}`);
  } else if (!skill.generated) {
    problems.push(`Claude Code skill was not generated by Planalot: ${skillPath}`);
  } else if (skill.skillVersion !== options.version) {
    problems.push(`Claude Code skill version is ${skill.skillVersion ?? "missing"}, expected ${options.version}.`);
  } else if (skill.skillRevision !== SKILL_REVISION) {
    problems.push(`Claude Code skill revision is ${skill.skillRevision ?? "missing"}, expected ${SKILL_REVISION}.`);
  }

  if (legacyCommand.exists && legacyCommand.generated) {
    if (legacyCommand.skillVersion !== options.version) {
      problems.push(`Generated legacy Claude Code command version is ${legacyCommand.skillVersion ?? "missing"}, expected ${options.version}.`);
    }
    if (legacyCommand.skillRevision !== SKILL_REVISION) {
      problems.push(`Generated legacy Claude Code command revision is ${legacyCommand.skillRevision ?? "missing"}, expected ${SKILL_REVISION}.`);
    }
  }

  return {
    localVersion: options.version,
    skillPath,
    commandPath,
    skill,
    legacyCommand,
    inSync: problems.length === 0,
    problems,
  };
}

async function writeGeneratedFile(path: string, content: string, force: boolean): Promise<void> {
  if (existsSync(path) && !force) {
    const current = readFileSync(path, "utf8");
    if (!current.includes(MARKER)) {
      throw new Error(`Refusing to overwrite non-planalot file at ${path}. Re-run with --force if this is intentional.`);
    }
  }

  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFile(path, content, "utf8");
}

async function maybeWriteLegacyCommand(commandPath: string, options: InstallCcOptions): Promise<boolean> {
  if (!existsSync(commandPath) && !options.force) return false;
  await writeGeneratedFile(commandPath, buildLegacyPlanalotCommand(options.cliPath, options.version), options.force === true);
  return true;
}

function buildPlanalotSkill(cliPath: string, version: string): string {
  const command = shellCommandForCli(cliPath);
  return `---
name: planalot
description: Use when the user asks to create, continue, review, or implement a Planalot plan workspace from Claude Code.
planalot_version: ${version}
planalot_skill_revision: ${SKILL_REVISION}
---

# Planalot

${MARKER}. Re-run \`planalot install cc\` after updating or moving Planalot.

Installed Planalot version: \`${version}\`.

User request / arguments:

\`\`\`
$ARGUMENTS
\`\`\`

## Purpose

Planalot is a local second-brain planning workspace. It stores durable plans under \`~/.planalot/plans/<id>\`, with \`manifest.json\`, \`feedback.json\`, and plan-authored files under \`requirements/\`, \`design/\`, and \`tasks/\`. Use the CLI as the tool-like interface from Claude Code.

## Current Claude Code Harness Boundary

This integration is intentionally non-MCP. Claude Code interacts with Planalot by running CLI commands. To receive browser feedback live you must **attach as a harness** and keep that process running in the background — otherwise the browser shows "No harness connected" and every feedback send fails.

## Workflow — route on the request, then drive ONE plan

First decide intent from the arguments and conversation:

- The argument is a markdown file path (e.g. \`PLAN.md\`) → **import** it.
- The user said "continue/resume <name>" → **find** then **read**.
- Otherwise → **create** a new plan and author its requirements.

### 1. Create / import / continue

\`\`\`powershell
# new plan
${command} create --name "Plan Name" --json
# from an existing file (Planalot copies it and owns it after)
${command} import "PLAN.md" --name "Plan Name" --json
# continue: find one match, then read everything before changing anything
${command} find "payments" --status planning --json
${command} read <planId> --all --json
\`\`\`

Note the returned \`planId\`; every later command uses it.

### 2. Attach as the harness — REQUIRED, run in the BACKGROUND

Launch this with your long-running-task mechanism (run the Bash command with \`run_in_background: true\`) and keep it alive for the whole session. It registers you with Planalot (the browser now shows you connected and driving) and streams feedback as one JSON object per line:

\`\`\`powershell
${command} attach <planId> --type claude-code --drive
\`\`\`

Planalot gives this instance a stable friendly name (e.g. \`amber-otter\`) shown in the browser's harness list and "Send to" dropdown, and reuses it for this working directory across plans and reconnects. To choose your own name, add \`--name "<name>"\`.

The first printed JSON line is \`{"type":"attached","name":"…"}\` — note that name. Later lines are events; lines with \`"type":"feedback.sent"\` or \`"type":"feedback.requested"\` are user feedback you must act on (step 4). Keep reading the background task's output across turns.

### 3. Author the plan, then open the browser

As the driver you hold the plan's edit lease. Write layered files via stdin — on PowerShell use \`-Raw\` and UTF-8 to avoid mangling content:

\`\`\`powershell
Get-Content -Raw updated-index.md | ${command} write <planId> requirements/index.md --stdin --json
${command} open <planId>
\`\`\`

Resolve top-down: \`requirements/\` → \`design/\` → \`tasks/\`.

### 4. Handle each feedback round

When the background \`attach\` stream prints a feedback event:

1. Read current files if needed: \`${command} read <planId> --all --json\`.
2. Apply changes with \`write\` (you are the addressed harness and hold the **exclusive edit lease** for this round — other harnesses are locked out until you respond).
3. Return the result as JSON via stdin (\`write\`/\`feedback-result\` automatically use your attached identity):

\`\`\`powershell
Get-Content -Raw feedback-result.json | ${command} feedback-result <planId> --stdin --json
\`\`\`

### 5. Finish

\`\`\`powershell
# hand off for implementation once feedback is resolved
${command} implement <planId> --json
# when fully done with the plan, stop the background attach and deregister
${command} detach <planId>
\`\`\`

## Layered Plan Contract

Resolve top-down: \`requirements/\` -> \`design/\` -> \`tasks/\`.

- \`requirements/\`: goals, business rules, constraints, acceptance criteria, non-goals, open questions.
- \`design/\`: architecture, UX flows, data model, APIs, tradeoffs, risks, rejected alternatives.
- \`tasks/\`: implementation slices, dependencies, file ownership, verification commands, rollout notes.

If requirements change, reconcile design/tasks. If design changes, reconcile tasks. Do not silently change requirements because of downstream feedback; ask a question or explain the conflict.

## Feedback Result Protocol

Planalot sends feedback requests as markdown and expects only valid JSON back through \`feedback-result\`.

The result shape is:

\`\`\`json
{
  "schemaVersion": 1,
  "feedbackSessionId": "fs_...",
  "fileChanges": [
    {
      "path": "requirements/index.md",
      "operation": "updated",
      "feedbackItemIds": ["fb_..."],
      "content": "optional full file content",
      "alreadyApplied": false
    }
  ],
  "responses": [
    {
      "id": "r_...",
      "kind": "question",
      "feedbackItemIds": ["fb_..."],
      "layer": "requirements",
      "text": "Question, clarification, or insight.",
      "expectsUserFollowUp": true,
      "suggestedAnswers": []
    }
  ]
}
\`\`\`

## Constraints

- Planalot owns the source of truth once a plan is created or imported.
- Plan-authored files must be under \`requirements/\`, \`design/\`, or \`tasks/\`.
- \`requirements/index.md\` is required and canonical.
- Default discovery excludes expired plans; use \`--include-expired\` only when the user asks for old plans.
- Do not treat feedback as known until it appears in the \`attach\` stream or chat.
- Keep a background \`attach\` running to appear connected and receive feedback; stop it with \`detach\` when finished. If it stops, the browser shows "No harness connected".
- A feedback round is addressed to one harness, which holds an exclusive edit lease — the daemon rejects plan writes from anyone else with HTTP 409. Respond with \`feedback-result\` to release it.
`;
}

function buildLegacyPlanalotCommand(cliPath: string, version: string): string {
  return `---
description: Use the Planalot Claude Code skill to create, continue, review, or implement a Planalot plan workspace.
---

<!-- ${MARKER}. Re-run \`planalot install cc\` after updating or moving Planalot. -->
<!-- planalot_version: ${version} -->
<!-- planalot_skill_revision: ${SKILL_REVISION} -->

# Planalot

Claude Code now prefers skills at \`~/.claude/skills/planalot/SKILL.md\`. If this legacy command is invoked, follow the same workflow as the Planalot skill:

- Create or import plans with the Planalot CLI.
- Read and write Planalot-owned files under \`requirements/\`, \`design/\`, and \`tasks/\`.
- Open the browser UI with \`open <planId>\`.
- Use \`wait-feedback\` and \`feedback-result\` for browser feedback.

User request / arguments:

\`\`\`
$ARGUMENTS
\`\`\`
`;
}

function readVersionProbe(path: string, localVersion: string): CcVersionProbe {
  const exists = existsSync(path);
  const generated = exists && readFileSync(path, "utf8").includes(MARKER);
  const skillVersion = readSkillVersion(path);
  const skillRevision = readSkillRevision(path);
  return {
    path,
    exists,
    generated,
    ...(skillVersion === undefined ? {} : { skillVersion }),
    ...(skillRevision === undefined ? {} : { skillRevision }),
    matches: exists && skillVersion === localVersion && skillRevision === SKILL_REVISION,
  };
}

function readSkillVersion(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  const content = readFileSync(path, "utf8");
  const frontmatterMatch = content.match(/^planalot_version:\s*["']?([^"'\r\n]+)["']?\s*$/m);
  if (frontmatterMatch?.[1]) return frontmatterMatch[1].trim();
  return content.match(/<!--\s*planalot_version:\s*([^>\r\n]+)\s*-->/)?.[1]?.trim();
}

function readSkillRevision(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  const content = readFileSync(path, "utf8");
  const frontmatterMatch = content.match(/^planalot_skill_revision:\s*["']?([^"'\r\n]+)["']?\s*$/m);
  if (frontmatterMatch?.[1]) return frontmatterMatch[1].trim();
  return content.match(/<!--\s*planalot_skill_revision:\s*([^>\r\n]+)\s*-->/)?.[1]?.trim();
}

function shellCommandForCli(cliPath: string): string {
  const node = quoteForShell(process.execPath);
  const cli = quoteForShell(cliPath);
  return `${node} ${cli}`;
}

function quoteForShell(value: string): string {
  if (/^[A-Za-z0-9_./:=-]+$/.test(value)) return value;
  return `"${value.replace(/"/g, '\\"')}"`;
}
