import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const MARKER = "Generated by planalot install pi";

export interface InstallPiOptions {
  cliPath: string;
  force?: boolean;
}

export async function installPiExtension(options: InstallPiOptions): Promise<string> {
  const extensionPath = join(homedir(), ".pi", "agent", "extensions", "planalot", "index.ts");

  if (existsSync(extensionPath) && !options.force) {
    const current = readFileSync(extensionPath, "utf8");
    if (!current.includes(MARKER)) {
      throw new Error(
        `Refusing to overwrite non-planalot extension at ${extensionPath}. Re-run with --force if this is intentional.`,
      );
    }
  }

  await mkdir(dirname(extensionPath), { recursive: true, mode: 0o700 });
  await writeFile(
    extensionPath,
    buildPiExtensionSource({ nodePath: process.execPath, cliPath: options.cliPath }),
    "utf8",
  );
  return extensionPath;
}

function buildPiExtensionSource(config: { nodePath: string; cliPath: string }): string {
  return `/**
 * ${MARKER}.
 * Re-run \`planalot install pi\` after updating or moving planalot.
 */
import { existsSync, readFileSync } from "node:fs";
import { mkdirSync } from "node:fs";
import { homedir, release } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawn } from "node:child_process";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

const PLANALOT_NODE = ${JSON.stringify(config.nodePath)};
const PLANALOT_CLI = ${JSON.stringify(config.cliPath)};
const PLANALOT_VERSION = "0.1.0";

type DaemonMetadata = { pid: number; port: number; token: string; startedAt: number; version: string };
type LiteAnnotation = { id: string; type: string; originalText: string; comment?: string; label?: string; blockId?: string };
type ConversationMessage = { id: string; role: string; kind: string; text: string; annotations?: LiteAnnotation[]; createdAt: number };
type FeedbackSuggestion = { id: string; label: string; description: string };
type FeedbackQuestion = { id: string; kind: "text" | "single-select" | "multi-select"; prompt: string; required?: boolean; suggestions?: FeedbackSuggestion[] };
type FeedbackAnswer = { questionId: string; text?: string; selectedSuggestionIds?: string[] };
type FeedbackBatch = { id: string; messageId: string; status: string; planVersionId: string; message: ConversationMessage; createdAt: number; updatedAt: number };
type FeedbackQuestionRequest = { id: string; feedbackBatchId?: string; planVersionId: string; questions: FeedbackQuestion[]; status: string; createdAt: number; answeredAt?: number };
type ServerEvent =
  | { type: "feedback.sent"; sessionId: string; message: ConversationMessage; batch: FeedbackBatch; targetHarnessId?: string }
  | { type: "feedback.answered"; sessionId: string; request: FeedbackQuestionRequest; answers: FeedbackAnswer[]; targetHarnessId?: string }
  | { type: "plan.accepted"; sessionId: string; message: ConversationMessage; targetHarnessId?: string }
  | { type: "plan.build"; sessionId: string; message: ConversationMessage; targetHarnessId?: string }
  | { type: "agent.message"; sessionId: string; message: ConversationMessage }
  | { type: "plan.changed"; sessionId: string; planText: string; hash: string }
  | { type: "session.status"; sessionId: string; status: string }
  | { type: "feedback.failed"; sessionId: string; error: string }
  | { type: string; sessionId?: string; targetHarnessId?: string };

type ActiveSession = {
  sessionId: string;
  harnessId: string;
  port: number;
  token: string;
  planFile: string;
  abort: AbortController;
  deliveredFeedback: Set<string>;
};

function metadataPath(): string {
  return join(homedir(), ".planalot", "daemon.json");
}

function daemonLogPath(): string {
  return join(homedir(), ".planalot", "daemon.log");
}

function readMetadata(): DaemonMetadata | null {
  try {
    return JSON.parse(readFileSync(metadataPath(), "utf8")) as DaemonMetadata;
  } catch {
    return null;
  }
}

async function isHealthy(meta: DaemonMetadata): Promise<boolean> {
  try {
    const response = await fetch(\`http://127.0.0.1:\${meta.port}/health\`, { signal: AbortSignal.timeout(500) });
    return response.ok;
  } catch {
    return false;
  }
}

async function ensureDaemon(): Promise<DaemonMetadata> {
  const existing = readMetadata();
  if (existing && await isHealthy(existing)) return existing;

  mkdirSync(dirname(daemonLogPath()), { recursive: true });
  const child = spawn(PLANALOT_NODE, [PLANALOT_CLI, "daemon"], {
    detached: true,
    stdio: "ignore",
    env: { ...process.env },
  });
  child.unref();

  const deadline = Date.now() + 5000;
  while (Date.now() < deadline) {
    await sleep(150);
    const meta = readMetadata();
    if (meta && await isHealthy(meta)) return meta;
  }
  throw new Error(\`Timed out starting planalot daemon. Check \${daemonLogPath()}.\`);
}

async function createSession(meta: DaemonMetadata, ctx: ExtensionContext, planFile: string): Promise<{ sessionId: string; url: string }> {
  const cleanPlanFile = stripAtPrefix(planFile).trim();
  assertMarkdownPath(cleanPlanFile);

  const absolute = resolve(ctx.cwd, cleanPlanFile);
  if (!existsSync(absolute)) {
    throw new Error(\`Planalot only watches existing plan files. Create \${cleanPlanFile} first, then open it with /planalot \${cleanPlanFile} or planalot_open_plan.\`);
  }

  const text = readFileSync(absolute, "utf8");
  const response = await fetch(\`http://127.0.0.1:\${meta.port}/sessions\`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: \`Bearer \${meta.token}\`,
    },
    body: JSON.stringify({
      runtime: "pi",
      cwd: ctx.cwd,
      planFile: cleanPlanFile,
      planText: text,
      transport: {
        kind: "pi",
        sessionId: ctx.sessionManager.getSessionId?.(),
        sessionFile: ctx.sessionManager.getSessionFile?.(),
      },
    }),
  });
  if (!response.ok) throw new Error(\`planalot session failed: \${response.status} \${await response.text()}\`);
  return await response.json() as { sessionId: string; url: string };
}

function openBrowser(url: string): boolean {
  const browser = process.env.PLANALOT_BROWSER || process.env.BROWSER;
  const platform = process.platform;
  const wsl = platform === "linux" && release().toLowerCase().includes("microsoft");
  let command: string;
  let args: string[];

  if (browser) {
    if (platform === "darwin" && process.env.PLANALOT_BROWSER) {
      command = "open";
      args = ["-a", browser, url];
    } else if (platform === "win32" || wsl) {
      command = "cmd.exe";
      args = ["/c", "start", "", browser, url];
    } else {
      command = browser;
      args = [url];
    }
  } else if (platform === "win32" || wsl) {
    command = "cmd.exe";
    args = ["/c", "start", "", url];
  } else if (platform === "darwin") {
    command = "open";
    args = [url];
  } else {
    command = "xdg-open";
    args = [url];
  }

  try {
    const child = spawn(command, args, { detached: true, stdio: "ignore" });
    child.once("error", () => undefined);
    child.unref();
    return true;
  } catch {
    return false;
  }
}

function formatFeedback(message: ConversationMessage, planFile: string, batch?: FeedbackBatch): string {
  let text = \`Planalot browser feedback for \${planFile}:\\n\\n\${message.text.trim()}\`;
  if (batch) {
    text += \`\\n\\nFeedback batch id: \${batch.id}\`;
  }
  if (message.annotations?.length) {
    text += "\\n\\nAnnotations:";
    for (const annotation of message.annotations) {
      const where = annotation.blockId ? \` [\${annotation.blockId}]\` : "";
      if (annotation.type === "DELETION") {
        text += \`\\n-\${where} DELETE "\${annotation.originalText}"\`;
      } else if (annotation.label) {
        text += \`\\n-\${where} [\${annotation.label}] "\${annotation.originalText}"\`;
      } else {
        text += \`\\n-\${where} "\${annotation.originalText}"\`;
        if (annotation.comment) text += \`: \${annotation.comment}\`;
      }
    }
  }
  text += "\\n\\nYou may either update the plan file and call planalot_plan_updated, or ask the user follow-up questions with planalot_request_feedback. If you ask questions, every selectable suggestion must include a description detailed enough for the user to understand the choice.";
  return text;
}

function formatAnsweredFeedback(event: Extract<ServerEvent, { type: "feedback.answered" }>): string {
  const lines = event.answers.map((answer) => {
    const selected = answer.selectedSuggestionIds?.length ? \` selections=\${answer.selectedSuggestionIds.join(", ")}\` : "";
    const text = answer.text ? \` text=\"\${answer.text}\"\` : "";
    return \`- \${answer.questionId}:\${selected}\${text}\`;
  });
  return \`The user answered Planalot follow-up questions for feedback request \${event.request.id}.\\n\\n\${lines.join("\\n")}\\n\\nContinue addressing the feedback. If you update the plan file, call planalot_plan_updated.\`;
}

async function postJson(active: ActiveSession, action: string, body: unknown): Promise<unknown> {
  const response = await fetch(\`http://127.0.0.1:\${active.port}/sessions/\${active.sessionId}/\${action}\`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: \`Bearer \${active.token}\`,
    },
    body: JSON.stringify(body),
  });
  if (!response.ok) throw new Error(await response.text());
  return await response.json();
}

async function listenForFeedback(pi: ExtensionAPI, ctx: ExtensionContext, active: ActiveSession): Promise<void> {
  const params = new URLSearchParams({
    token: active.token,
    role: "harness",
    harnessId: active.harnessId,
    harnessType: "pi",
    label: active.planFile,
  });
  const response = await fetch(
    \`http://127.0.0.1:\${active.port}/sessions/\${active.sessionId}/events?\${params.toString()}\`,
    { signal: active.abort.signal },
  );
  if (!response.ok || !response.body) throw new Error(\`SSE failed: \${response.status}\`);

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  while (!active.abort.signal.aborted) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    let boundary = buffer.indexOf("\\n\\n");
    while (boundary !== -1) {
      const chunk = buffer.slice(0, boundary);
      buffer = buffer.slice(boundary + 2);
      handleSseChunk(pi, ctx, active, chunk);
      boundary = buffer.indexOf("\\n\\n");
    }
  }
}

function handleSseChunk(pi: ExtensionAPI, ctx: ExtensionContext, active: ActiveSession, chunk: string): void {
  const dataLine = chunk.split("\\n").find((line) => line.startsWith("data: "));
  if (!dataLine) return;
  const event = JSON.parse(dataLine.slice(6)) as ServerEvent;

  // Self-filter targeted delivery: ignore events addressed to a different harness
  // instance. Untargeted events (no targetHarnessId) are handled by all, for back-compat.
  const directed = (event as { targetHarnessId?: string }).targetHarnessId;
  if (directed && directed !== active.harnessId) return;

  if (event.type === "feedback.sent") {
    if (active.deliveredFeedback.has(event.message.id)) return;
    active.deliveredFeedback.add(event.message.id);
    sendHarnessMessage(pi, ctx, formatFeedback(event.message, active.planFile, event.batch), "Planalot feedback sent to agent");
    return;
  }

  if (event.type === "feedback.answered") {
    if (active.deliveredFeedback.has(event.request.id)) return;
    active.deliveredFeedback.add(event.request.id);
    sendHarnessMessage(pi, ctx, formatAnsweredFeedback(event), "Planalot answers sent to agent");
    return;
  }

  if (event.type === "plan.accepted") {
    sendHarnessMessage(pi, ctx, "The user accepted the Planalot plan. Do not implement yet. Await the user to explicitly say implement/build.", "Planalot acceptance sent to agent");
    return;
  }

  if (event.type === "plan.build") {
    sendHarnessMessage(pi, ctx, "The user accepted the Planalot plan and pressed Build. Move to the implementation phase using the accepted plan.", "Planalot build request sent to agent");
  }
}

function sendHarnessMessage(pi: ExtensionAPI, ctx: ExtensionContext, text: string, notification: string): void {
  try {
    if (ctx.isIdle()) pi.sendUserMessage(text);
    else pi.sendUserMessage(text, { deliverAs: "followUp" });
    ctx.ui.notify(notification, "info");
  } catch (error) {
    ctx.ui.notify(\`Planalot failed to send message: \${error instanceof Error ? error.message : String(error)}\`, "error");
  }
}

function stripAtPrefix(path: string): string {
  return path.startsWith("@") ? path.slice(1) : path;
}

function isMarkdownPath(path: string): boolean {
  return /\\.(md|mdx)$/i.test(stripAtPrefix(path).trim());
}

function assertMarkdownPath(path: string): void {
  if (!isMarkdownPath(path)) {
    throw new Error("Planalot requires an existing .md or .mdx plan file path.");
  }
}

function sendBootstrapRequest(pi: ExtensionAPI, ctx: ExtensionContext, request: string): void {
  const trimmed = request.trim();
  const suggestedPath = isMarkdownPath(trimmed) ? stripAtPrefix(trimmed) : "PLAN.md";
  const prompt = \`Start a Planalot planning run for this request:\n\n\${trimmed || "Start a new plan."}\n\nUse the current conversation context plus the request above.\n\nRequirements:\n- Create or update a markdown plan file inside the current workspace first.\n- If the request looks like a desired plan file path, use that path: \${suggestedPath}.\n- The plan file must contain a useful initial plan with goal, context, approach, implementation slices, verification, and open questions/risks.\n- Do not call planalot_open_plan until the plan file exists.\n- After creating/updating the file, call planalot_open_plan with the exact existing .md/.mdx file path.\n- planalot_open_plan is strict: it only opens and watches existing markdown files; it never creates them.\`;

  if (ctx.isIdle()) pi.sendUserMessage(prompt);
  else pi.sendUserMessage(prompt, { deliverAs: "followUp" });
  ctx.ui.notify("Planalot asked the agent to create a plan file first.", "info");
}

function hasExistingMarkdownPlan(ctx: ExtensionContext, input: string): boolean {
  if (!isMarkdownPath(input)) return false;
  return existsSync(resolve(ctx.cwd, stripAtPrefix(input).trim()));
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export default function planalotPiExtension(pi: ExtensionAPI): void {
  let currentCtx: ExtensionContext | undefined;
  const activeSessions = new Map<string, ActiveSession>();

  async function openPlan(planFile: string, ctx: ExtensionContext): Promise<ActiveSession> {
    const meta = await ensureDaemon();
    const session = await createSession(meta, ctx, planFile);
    const previous = activeSessions.get(session.sessionId);
    previous?.abort.abort();

    const harnessId = ctx.sessionManager.getSessionId?.() ?? session.sessionId;
    const active: ActiveSession = {
      sessionId: session.sessionId,
      harnessId,
      port: meta.port,
      token: meta.token,
      planFile: stripAtPrefix(planFile).trim(),
      abort: new AbortController(),
      deliveredFeedback: new Set(),
    };
    activeSessions.set(session.sessionId, active);
    void listenForFeedback(pi, ctx, active).catch((error) => {
      if (!active.abort.signal.aborted) ctx.ui.notify(\`Planalot feedback bridge stopped: \${error instanceof Error ? error.message : String(error)}\`, "warning");
    });

    const opened = openBrowser(session.url);
    ctx.ui.notify(opened ? \`Planalot opened \${active.planFile}\` : \`Planalot URL: \${session.url}\`, opened ? "info" : "warning");
    return active;
  }

  pi.on("session_start", (_event, ctx) => {
    currentCtx = ctx;
    ctx.ui.setStatus("planalot", ctx.ui.theme.fg("muted", "planalot"));
  });

  pi.on("session_shutdown", () => {
    for (const session of activeSessions.values()) session.abort.abort();
    activeSessions.clear();
    currentCtx = undefined;
  });

  pi.registerCommand("planalot", {
    description: "Open an existing markdown plan file, or ask the agent to create one first",
    handler: async (args, ctx) => {
      currentCtx = ctx;
      const input = args.trim();
      if (!hasExistingMarkdownPlan(ctx, input)) {
        sendBootstrapRequest(pi, ctx, input);
        return;
      }
      await openPlan(input, ctx);
    },
  });

  function getActiveSession(sessionId?: string): ActiveSession {
    if (sessionId) {
      const active = activeSessions.get(sessionId);
      if (!active) throw new Error(\`No active Planalot session found for \${sessionId}.\`);
      return active;
    }
    const latest = Array.from(activeSessions.values()).at(-1);
    if (!latest) throw new Error("No active Planalot session. Open a plan with planalot_open_plan first.");
    return latest;
  }

  pi.registerTool({
    name: "planalot_open_plan",
    label: "Open Planalot",
    description: "Open a Planalot browser session for an existing markdown plan file so the user can annotate and send feedback.",
    promptSnippet: "Open Planalot for interactive browser feedback on an existing markdown plan file.",
    promptGuidelines: [
      "Use planalot_open_plan after writing or updating a substantial markdown plan that needs user feedback in the browser.",
      "The planalot_open_plan filePath parameter is required and must be an existing .md or .mdx file inside the current workspace.",
      "Never expect planalot_open_plan to create a plan file; create or update the markdown plan file first, then open it with planalot_open_plan.",
      "When the user says something like '/planalot lets start a new plan', create the plan file first, then call planalot_open_plan with that path.",
    ],
    parameters: Type.Object({
      filePath: Type.String({ description: "Existing markdown plan path relative to the workspace, e.g. PLAN.md" }),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      currentCtx = ctx;
      const planFile = params.filePath.trim();
      const active = await openPlan(planFile, ctx);
      return {
        content: [{ type: "text", text: \`Opened Planalot for \${active.planFile}. Browser feedback will be sent back to this Pi session.\` }],
        details: { sessionId: active.sessionId, planFile: active.planFile, version: PLANALOT_VERSION },
      };
    },
  });

  pi.registerTool({
    name: "planalot_plan_updated",
    label: "Notify Planalot Plan Updated",
    description: "Tell Planalot that the agent updated the watched plan file so it should read, diff, and version it immediately.",
    promptSnippet: "Notify Planalot immediately after editing a watched plan file.",
    promptGuidelines: [
      "Use planalot_plan_updated immediately after updating a plan file that is open in Planalot.",
      "The daemon also watches files with a debounce, but this tool provides immediate harness-side intent.",
    ],
    parameters: Type.Object({
      sessionId: Type.Optional(Type.String({ description: "Planlot session id; omit to use the latest active session" })),
    }),
    async execute(_toolCallId, params) {
      const active = getActiveSession(params.sessionId);
      await postJson(active, "plan-updated", { harnessId: active.harnessId });
      return { content: [{ type: "text", text: \`Notified Planalot that \${active.planFile} was updated.\` }], details: { sessionId: active.sessionId } };
    },
  });

  pi.registerTool({
    name: "planalot_request_feedback",
    label: "Request Planalot Feedback",
    description: "Ask the Planalot browser user a package of follow-up feedback questions with optional suggestions.",
    promptSnippet: "Ask the Planalot user clarifying feedback questions before revising the plan.",
    promptGuidelines: [
      "Use planalot_request_feedback when Planalot feedback is ambiguous and user clarification is needed before updating the plan.",
      "Every selectable suggestion must include a description detailed enough to explain the choice based on the conversation.",
      "If the user appears misaligned or the option is nuanced, spend more effort in the suggestion description. If aligned and obvious, keep it short.",
    ],
    parameters: Type.Object({
      sessionId: Type.Optional(Type.String({ description: "Planlot session id; omit to use the latest active session" })),
      feedbackBatchId: Type.Optional(Type.String({ description: "Feedback batch id being clarified, if known" })),
      questions: Type.Array(Type.Object({
        id: Type.String(),
        kind: Type.String({ description: "text, single-select, or multi-select" }),
        prompt: Type.String(),
        required: Type.Optional(Type.Boolean()),
        suggestions: Type.Optional(Type.Array(Type.Object({
          id: Type.String(),
          label: Type.String(),
          description: Type.String({ description: "Required detailed explanation for this choice" }),
        }))),
      })),
    }),
    async execute(_toolCallId, params) {
      const active = getActiveSession(params.sessionId);
      const result = await postJson(active, "feedback-requested", { feedbackBatchId: params.feedbackBatchId, questions: params.questions });
      return { content: [{ type: "text", text: "Requested Planalot user feedback. Wait for feedback.answered before continuing." }], details: result };
    },
  });
}
`;
}
