import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const MARKER = "Generated by planalot install codex";
const PLUGIN_NAME = "planalot";
const MARKETPLACE_NAME = "personal";

export interface InstallCodexOptions {
  cliPath: string;
  force?: boolean;
}

export interface InstallCodexResult {
  pluginPath: string;
  manifestPath: string;
  marketplacePath: string;
}

interface MarketplaceEntry {
  name: string;
  source: {
    source: "local";
    path: string;
  };
  policy: {
    installation: "AVAILABLE";
    authentication: "ON_INSTALL";
  };
  category: string;
}

interface Marketplace {
  name?: string;
  interface?: {
    displayName?: string;
    [key: string]: unknown;
  };
  plugins?: MarketplaceEntry[];
  [key: string]: unknown;
}

export async function installCodexExtension(options: InstallCodexOptions): Promise<InstallCodexResult> {
  const pluginPath = join(homedir(), "plugins", PLUGIN_NAME);
  const manifestPath = join(pluginPath, ".codex-plugin", "plugin.json");
  const skillPath = join(pluginPath, "skills", PLUGIN_NAME, "SKILL.md");
  const marketplacePath = join(homedir(), ".agents", "plugins", "marketplace.json");

  ensurePlanlotPluginManifestIsSafe(manifestPath, options.force === true);

  await writeGeneratedFile(manifestPath, JSON.stringify(buildPluginManifest(), null, 2) + "\n", true);
  await writeGeneratedFile(skillPath, buildSkillSource(options.cliPath), options.force === true);
  await upsertPersonalMarketplace(marketplacePath, options.force === true);

  return { pluginPath, manifestPath, marketplacePath };
}

function ensurePlanlotPluginManifestIsSafe(path: string, force: boolean): void {
  if (!existsSync(path) || force) return;

  try {
    const current = JSON.parse(readFileSync(path, "utf8")) as { name?: unknown };
    if (current.name === PLUGIN_NAME) return;
  } catch {
    // Fall through to the refusal below.
  }

  throw new Error(`Refusing to overwrite non-planalot Codex plugin at ${path}. Re-run with --force if this is intentional.`);
}

async function writeGeneratedFile(path: string, content: string, force: boolean): Promise<void> {
  if (existsSync(path) && !force) {
    const current = readFileSync(path, "utf8");
    if (!current.includes(MARKER)) {
      throw new Error(`Refusing to overwrite non-planalot file at ${path}. Re-run with --force if this is intentional.`);
    }
  }

  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFile(path, content, "utf8");
}

function buildPluginManifest(): unknown {
  return {
    name: PLUGIN_NAME,
    version: "0.1.0",
    description: "Open local markdown plans in the Planalot browser review UI from Codex.",
    author: {
      name: "Local developer",
    },
    keywords: ["planalot", "planning", "feedback", "codex"],
    skills: "./skills/",
    interface: {
      displayName: "Planalot",
      shortDescription: "Open markdown plans in a local browser feedback UI.",
      longDescription:
        "Use Planalot from Codex to create or open markdown plans, start the local Planalot daemon, and review plans in a browser with annotations and feedback history.",
      developerName: "Local developer",
      category: "Productivity",
      capabilities: ["Interactive", "Read", "Write"],
      defaultPrompt: [
        "Open this plan in Planalot",
        "Create a plan and review it in Planalot",
        "Use Planalot for browser feedback on this task",
      ],
      brandColor: "#2563EB",
    },
  };
}

function buildSkillSource(cliPath: string): string {
  const command = shellCommandForCli(cliPath);
  return `---
name: planalot
description: Use when the user asks to create, continue, review, or implement a Planalot plan workspace from Codex.
---

# Planalot

${MARKER}. Re-run \`planalot install codex\` after updating or moving Planalot.

## Purpose

Planalot is a local second-brain planning workspace. It stores durable plans under \`~/.planalot/plans/<id>\`, with \`manifest.json\`, \`feedback.json\`, \`index.md\`, and optional sibling \`.md\` / \`.html\` plan files. Use the CLI as the tool-like interface from Codex.

## Current Codex Harness Boundary

This integration is intentionally non-MCP. Codex interacts with Planalot by running CLI commands and reading their output. Browser feedback reaches Codex only when a CLI command such as \`wait-feedback\` prints it, or when the user pastes it into chat.

## Workflow

1. For "continue the payments plan", search first:

\`\`\`powershell
${command} find "payments" --status planning --json
\`\`\`

2. If one plan matches, read all plan files before continuing:

\`\`\`powershell
${command} read <planId> --all --json
\`\`\`

3. To start a new plan:

\`\`\`powershell
${command} create --name "Plan Name" --json
\`\`\`

4. To import an existing plan file into Planalot-owned storage:

\`\`\`powershell
${command} import "PLAN.md" --name "Plan Name" --json
\`\`\`

5. To open the browser UI:

\`\`\`powershell
${command} open <planId>
\`\`\`

6. To wait for browser feedback:

\`\`\`powershell
${command} wait-feedback <planId> --timeout 600 --json
\`\`\`

7. To update plan files, write via stdin:

\`\`\`powershell
Get-Content updated-index.md | ${command} write <planId> index.md --stdin --json
\`\`\`

8. To hand off for implementation after feedback is resolved:

\`\`\`powershell
${command} implement <planId> --json
\`\`\`

## Constraints

- Planalot owns the source of truth once a plan is created or imported.
- Plan-authored files are top-level sibling \`.md\` or \`.html\` files only.
- \`index.md\` is required and canonical.
- Default discovery excludes expired plans; use \`--include-expired\` only when the user asks for old plans.
- Do not treat feedback as known until it appears in CLI output or chat.
`;
}

async function upsertPersonalMarketplace(path: string, force: boolean): Promise<void> {
  const marketplace = readMarketplace(path);
  marketplace.name ??= MARKETPLACE_NAME;
  marketplace.interface ??= { displayName: "Personal" };
  marketplace.interface.displayName ??= "Personal";
  marketplace.plugins ??= [];

  if (!Array.isArray(marketplace.plugins)) {
    throw new Error(`${path} field 'plugins' must be an array.`);
  }

  const entry = buildMarketplaceEntry();
  const existingIndex = marketplace.plugins.findIndex((candidate) => candidate?.name === PLUGIN_NAME);
  if (existingIndex >= 0) {
    const existing = marketplace.plugins[existingIndex]!;
    const sameLocalPath = existing.source?.source === "local" && existing.source.path === entry.source.path;
    if (!force && !sameLocalPath) {
      throw new Error(`Marketplace entry '${PLUGIN_NAME}' already points at ${existing.source?.path ?? "unknown"}. Re-run with --force if this is intentional.`);
    }
    marketplace.plugins[existingIndex] = entry;
  } else {
    marketplace.plugins.push(entry);
  }

  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFile(path, JSON.stringify(marketplace, null, 2) + "\n", "utf8");
}

function readMarketplace(path: string): Marketplace {
  if (!existsSync(path)) return { name: MARKETPLACE_NAME, interface: { displayName: "Personal" }, plugins: [] };
  const payload = JSON.parse(readFileSync(path, "utf8")) as Marketplace;
  if (typeof payload !== "object" || payload === null || Array.isArray(payload)) {
    throw new Error(`${path} must contain a JSON object.`);
  }
  return payload;
}

function buildMarketplaceEntry(): MarketplaceEntry {
  return {
    name: PLUGIN_NAME,
    source: {
      source: "local",
      path: `./plugins/${PLUGIN_NAME}`,
    },
    policy: {
      installation: "AVAILABLE",
      authentication: "ON_INSTALL",
    },
    category: "Productivity",
  };
}

function shellCommandForCli(cliPath: string): string {
  const node = quoteForShell(process.execPath);
  const cli = quoteForShell(cliPath);
  return `${node} ${cli}`;
}

function quoteForShell(value: string): string {
  if (/^[A-Za-z0-9_./:=-]+$/.test(value)) return value;
  return `"${value.replace(/"/g, '\\"')}"`;
}
