import { existsSync, readdirSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const MARKER = "Generated by planalot install codex";
const PLUGIN_NAME = "planalot";
const MARKETPLACE_NAME = "personal";
const SKILL_REVISION = "harness-attach-v3";

export interface InstallCodexOptions {
  cliPath: string;
  version: string;
  force?: boolean;
}

export interface InstallCodexResult {
  pluginPath: string;
  manifestPath: string;
  marketplacePath: string;
}

export interface CheckCodexOptions {
  version: string;
}

export interface CodexVersionProbe {
  path: string;
  exists: boolean;
  manifestVersion?: string;
  skillVersion?: string;
  skillRevision?: string;
  matches: boolean;
}

export interface CheckCodexResult {
  localVersion: string;
  pluginPath: string;
  marketplacePath: string;
  source: CodexVersionProbe;
  cache: CodexVersionProbe[];
  inSync: boolean;
  problems: string[];
}

interface MarketplaceEntry {
  name: string;
  source: {
    source: "local";
    path: string;
  };
  policy: {
    installation: "AVAILABLE";
    authentication: "ON_INSTALL";
  };
  category: string;
}

interface Marketplace {
  name?: string;
  interface?: {
    displayName?: string;
    [key: string]: unknown;
  };
  plugins?: MarketplaceEntry[];
  [key: string]: unknown;
}

export async function installCodexExtension(options: InstallCodexOptions): Promise<InstallCodexResult> {
  const pluginPath = join(homedir(), "plugins", PLUGIN_NAME);
  const manifestPath = join(pluginPath, ".codex-plugin", "plugin.json");
  const skillPath = join(pluginPath, "skills", PLUGIN_NAME, "SKILL.md");
  const marketplacePath = join(homedir(), ".agents", "plugins", "marketplace.json");

  ensurePlanlotPluginManifestIsSafe(manifestPath, options.force === true);

  await writeGeneratedFile(manifestPath, JSON.stringify(buildPluginManifest(options.version), null, 2) + "\n", true);
  await writeGeneratedFile(skillPath, buildSkillSource(options.cliPath, options.version), options.force === true);
  await upsertPersonalMarketplace(marketplacePath, options.force === true);

  return { pluginPath, manifestPath, marketplacePath };
}

export function checkCodexExtension(options: CheckCodexOptions): CheckCodexResult {
  const pluginPath = join(homedir(), "plugins", PLUGIN_NAME);
  const marketplacePath = join(homedir(), ".agents", "plugins", "marketplace.json");
  const source = readVersionProbe(pluginPath, options.version);
  const cacheRoot = join(homedir(), ".codex", "plugins", "cache", MARKETPLACE_NAME, PLUGIN_NAME);
  const cache = readCacheProbes(cacheRoot, options.version);
  const problems: string[] = [];

  if (!source.exists) {
    problems.push(`Codex plugin source is missing: ${pluginPath}`);
  } else {
    pushProbeProblems(problems, "Codex plugin source", source, options.version);
  }

  if (cache.length === 0) {
    problems.push(`Codex plugin cache is missing: ${cacheRoot}`);
  } else {
    for (const probe of cache) pushProbeProblems(problems, `Codex plugin cache ${probe.path}`, probe, options.version);
  }

  return {
    localVersion: options.version,
    pluginPath,
    marketplacePath,
    source,
    cache,
    inSync: problems.length === 0,
    problems,
  };
}

function ensurePlanlotPluginManifestIsSafe(path: string, force: boolean): void {
  if (!existsSync(path) || force) return;

  try {
    const current = JSON.parse(readFileSync(path, "utf8")) as { name?: unknown };
    if (current.name === PLUGIN_NAME) return;
  } catch {
    // Fall through to the refusal below.
  }

  throw new Error(`Refusing to overwrite non-planalot Codex plugin at ${path}. Re-run with --force if this is intentional.`);
}

async function writeGeneratedFile(path: string, content: string, force: boolean): Promise<void> {
  if (existsSync(path) && !force) {
    const current = readFileSync(path, "utf8");
    if (!current.includes(MARKER)) {
      throw new Error(`Refusing to overwrite non-planalot file at ${path}. Re-run with --force if this is intentional.`);
    }
  }

  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFile(path, content, "utf8");
}

function buildPluginManifest(version: string): unknown {
  return {
    name: PLUGIN_NAME,
    version,
    description: "Open local markdown plans in the Planalot browser review UI from Codex.",
    author: {
      name: "Local developer",
    },
    keywords: ["planalot", "planning", "feedback", "codex"],
    skills: "./skills/",
    interface: {
      displayName: "Planalot",
      shortDescription: "Open markdown plans in a local browser feedback UI.",
      longDescription:
        "Use Planalot from Codex to create or open markdown plans, start the local Planalot daemon, and review plans in a browser with annotations and feedback history.",
      developerName: "Local developer",
      category: "Productivity",
      capabilities: ["Interactive", "Read", "Write"],
      defaultPrompt: [
        "Open this plan in Planalot",
        "Create a plan and review it in Planalot",
        "Use Planalot for browser feedback on this task",
      ],
      brandColor: "#2563EB",
    },
  };
}

function buildSkillSource(cliPath: string, version: string): string {
  const command = shellCommandForCli(cliPath);
  return `---
name: planalot
description: Use when the user asks to create, continue, review, or implement a Planalot plan workspace from Codex.
planalot_version: ${version}
planalot_skill_revision: ${SKILL_REVISION}
---

# Planalot

${MARKER}. Re-run \`planalot install codex\` after updating or moving Planalot.

Installed Planalot version: \`${version}\`.

## Purpose

Planalot is a local second-brain planning workspace. It stores durable plans under \`~/.planalot/plans/<id>\`, with \`manifest.json\`, \`feedback.json\`, and plan-authored files under \`requirements/\`, \`design/\`, and \`tasks/\`. Use the CLI as the tool-like interface from Codex.

## Current Codex Harness Boundary

This integration is intentionally non-MCP. Codex interacts with Planalot by running CLI commands. To receive browser feedback and appear connected you **attach as a harness**; if your runtime can't keep a background process streaming, run \`attach\` in a separate terminal and paste the feedback lines, or poll with \`wait-feedback\`.

## Workflow — route on the request, then drive ONE plan

First decide intent: a markdown file path → **import**; "continue/resume <name>" → **find** then **read**; otherwise → **create**.

### 1. Create / import / continue

\`\`\`powershell
${command} create --name "Plan Name" --json
${command} import "PLAN.md" --name "Plan Name" --json
${command} find "payments" --status planning --json
${command} read <planId> --all --json
\`\`\`

Note the returned \`planId\`.

### 2. Attach as the harness (keep running)

Run this and keep it alive — in the background if your runtime supports it, otherwise in a separate terminal. It registers you with Planalot (the browser shows you connected) and streams feedback as one JSON object per line:

\`\`\`powershell
${command} attach <planId> --type codex --drive
\`\`\`

Planalot gives this instance a stable friendly name (e.g. \`amber-otter\`) shown in the browser's harness list and "Send to" dropdown, reused for this working directory across plans. Add \`--name "<name>"\` to choose your own.

If you cannot keep it running, poll instead: \`${command} wait-feedback <planId> --timeout 600 --json\`.

### 3. Author the plan, then open the browser

\`\`\`powershell
Get-Content -Raw updated-index.md | ${command} write <planId> requirements/index.md --stdin --json
${command} open <planId>
\`\`\`

Resolve top-down: \`requirements/\` → \`design/\` → \`tasks/\`.

### 4. Handle each feedback round

When a feedback event appears (in the \`attach\` stream, \`wait-feedback\` output, or chat): read files if needed, apply changes with \`write\` (you hold the exclusive edit lease for the round), then return the result:

\`\`\`powershell
Get-Content -Raw feedback-result.json | ${command} feedback-result <planId> --stdin --json
\`\`\`

### 5. Finish

\`\`\`powershell
${command} implement <planId> --json
${command} detach <planId>
\`\`\`

## Layered Plan Contract

Resolve top-down: \`requirements/\` -> \`design/\` -> \`tasks/\`.

- \`requirements/\`: goals, business rules, constraints, acceptance criteria, non-goals, open questions.
- \`design/\`: architecture, UX flows, data model, APIs, tradeoffs, risks, rejected alternatives.
- \`tasks/\`: implementation slices, dependencies, file ownership, verification commands, rollout notes.

If requirements change, reconcile design/tasks. If design changes, reconcile tasks. Do not silently change requirements because of downstream feedback; ask a question or explain the conflict.

## Feedback Result Protocol

Planalot sends feedback requests as markdown and expects only valid JSON back through \`feedback-result\`.

The result shape is:

\`\`\`json
{
  "schemaVersion": 1,
  "feedbackSessionId": "fs_...",
  "fileChanges": [
    {
      "path": "requirements/index.md",
      "operation": "updated",
      "feedbackItemIds": ["fb_..."],
      "content": "optional full file content",
      "alreadyApplied": false
    }
  ],
  "responses": [
    {
      "id": "r_...",
      "kind": "question",
      "feedbackItemIds": ["fb_..."],
      "layer": "requirements",
      "text": "Question, clarification, or insight.",
      "expectsUserFollowUp": true,
      "suggestedAnswers": []
    }
  ]
}
\`\`\`

## Constraints

- Planalot owns the source of truth once a plan is created or imported.
- Plan-authored files must be under \`requirements/\`, \`design/\`, or \`tasks/\`.
- \`requirements/index.md\` is required and canonical.
- Default discovery excludes expired plans; use \`--include-expired\` only when the user asks for old plans.
- Do not treat feedback as known until it appears in the \`attach\` stream, \`wait-feedback\` output, or chat.
- Keep \`attach\` running to appear connected; stop it with \`detach\` when finished. If nothing is attached, the browser shows "No harness connected" and sends fail.
- A feedback round is addressed to one harness, which holds an exclusive edit lease — the daemon rejects plan writes from anyone else with HTTP 409. Respond with \`feedback-result\` to release it.
`;
}

function readCacheProbes(cacheRoot: string, localVersion: string): CodexVersionProbe[] {
  if (!existsSync(cacheRoot)) return [];
  return readdirSync(cacheRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => readVersionProbe(join(cacheRoot, entry.name), localVersion));
}

function readVersionProbe(pluginPath: string, localVersion: string): CodexVersionProbe {
  const manifestPath = join(pluginPath, ".codex-plugin", "plugin.json");
  const skillPath = join(pluginPath, "skills", PLUGIN_NAME, "SKILL.md");
  const manifestVersion = readManifestVersion(manifestPath);
  const skillVersion = readSkillVersion(skillPath);
  const skillRevision = readSkillRevision(skillPath);
  const exists = existsSync(pluginPath);
  return {
    path: pluginPath,
    exists,
    ...(manifestVersion === undefined ? {} : { manifestVersion }),
    ...(skillVersion === undefined ? {} : { skillVersion }),
    ...(skillRevision === undefined ? {} : { skillRevision }),
    matches: exists && manifestVersion === localVersion && skillVersion === localVersion && skillRevision === SKILL_REVISION,
  };
}

function readManifestVersion(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  const manifest = JSON.parse(readFileSync(path, "utf8")) as { version?: unknown };
  return typeof manifest.version === "string" ? manifest.version : undefined;
}

function readSkillVersion(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  const match = readFileSync(path, "utf8").match(/^planalot_version:\s*["']?([^"'\r\n]+)["']?\s*$/m);
  return match?.[1]?.trim();
}

function readSkillRevision(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  const match = readFileSync(path, "utf8").match(/^planalot_skill_revision:\s*["']?([^"'\r\n]+)["']?\s*$/m);
  return match?.[1]?.trim();
}

function pushProbeProblems(problems: string[], label: string, probe: CodexVersionProbe, localVersion: string): void {
  if (probe.manifestVersion !== localVersion) {
    problems.push(`${label} manifest version is ${probe.manifestVersion ?? "missing"}, expected ${localVersion}.`);
  }
  if (probe.skillVersion !== localVersion) {
    problems.push(`${label} skill version is ${probe.skillVersion ?? "missing"}, expected ${localVersion}.`);
  }
  if (probe.skillRevision !== SKILL_REVISION) {
    problems.push(`${label} skill revision is ${probe.skillRevision ?? "missing"}, expected ${SKILL_REVISION}.`);
  }
}

async function upsertPersonalMarketplace(path: string, force: boolean): Promise<void> {
  const marketplace = readMarketplace(path);
  marketplace.name ??= MARKETPLACE_NAME;
  marketplace.interface ??= { displayName: "Personal" };
  marketplace.interface.displayName ??= "Personal";
  marketplace.plugins ??= [];

  if (!Array.isArray(marketplace.plugins)) {
    throw new Error(`${path} field 'plugins' must be an array.`);
  }

  const entry = buildMarketplaceEntry();
  const existingIndex = marketplace.plugins.findIndex((candidate) => candidate?.name === PLUGIN_NAME);
  if (existingIndex >= 0) {
    const existing = marketplace.plugins[existingIndex]!;
    const sameLocalPath = existing.source?.source === "local" && existing.source.path === entry.source.path;
    if (!force && !sameLocalPath) {
      throw new Error(`Marketplace entry '${PLUGIN_NAME}' already points at ${existing.source?.path ?? "unknown"}. Re-run with --force if this is intentional.`);
    }
    marketplace.plugins[existingIndex] = entry;
  } else {
    marketplace.plugins.push(entry);
  }

  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFile(path, JSON.stringify(marketplace, null, 2) + "\n", "utf8");
}

function readMarketplace(path: string): Marketplace {
  if (!existsSync(path)) return { name: MARKETPLACE_NAME, interface: { displayName: "Personal" }, plugins: [] };
  const payload = JSON.parse(readFileSync(path, "utf8")) as Marketplace;
  if (typeof payload !== "object" || payload === null || Array.isArray(payload)) {
    throw new Error(`${path} must contain a JSON object.`);
  }
  return payload;
}

function buildMarketplaceEntry(): MarketplaceEntry {
  return {
    name: PLUGIN_NAME,
    source: {
      source: "local",
      path: `./plugins/${PLUGIN_NAME}`,
    },
    policy: {
      installation: "AVAILABLE",
      authentication: "ON_INSTALL",
    },
    category: "Productivity",
  };
}

function shellCommandForCli(cliPath: string): string {
  const node = quoteForShell(process.execPath);
  const cli = quoteForShell(cliPath);
  return `${node} ${cli}`;
}

function quoteForShell(value: string): string {
  if (/^[A-Za-z0-9_./:=-]+$/.test(value)) return value;
  return `"${value.replace(/"/g, '\\"')}"`;
}
