import { existsSync, readdirSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import {
  computeInSync,
  convergeWrite,
  readManifestVersion,
  readSkillRevision,
  readSkillVersion,
  shellCommandForCli,
  type ConvergeAction,
  type ConvergeReport,
  type ConvergeStep,
  type UnfixableDrift,
} from "@planalot/extension-kit";

const MARKER = "Generated by planalot install codex";
const PLUGIN_NAME = "planalot";
const MARKETPLACE_NAME = "personal";
const SKILL_REVISION = "harness-attach-v3";

export interface ConvergeCodexOptions {
  cliPath: string;
  version: string;
}

interface CodexVersionProbe {
  path: string;
  exists: boolean;
  manifestVersion?: string;
  skillVersion?: string;
  skillRevision?: string;
  matches: boolean;
}

interface MarketplaceEntry {
  name: string;
  source: {
    source: "local";
    path: string;
  };
  policy: {
    installation: "AVAILABLE";
    authentication: "ON_INSTALL";
  };
  category: string;
}

interface Marketplace {
  name?: string;
  interface?: {
    displayName?: string;
    [key: string]: unknown;
  };
  plugins?: MarketplaceEntry[];
  [key: string]: unknown;
}

export function installCodexExtension(options: ConvergeCodexOptions): Promise<ConvergeReport> {
  return converge(options, true);
}

export function checkCodexExtension(options: ConvergeCodexOptions): Promise<ConvergeReport> {
  return converge(options, false);
}

/**
 * Converge the Codex resources planalot owns:
 *   - plugins/planalot/.codex-plugin/plugin.json  → authoritative (re)write
 *   - plugins/planalot/skills/planalot/SKILL.md   → authoritative (re)write
 *   - ~/.agents/plugins/marketplace.json          → upsert OUR entry, keep others
 * The codex cache (~/.codex/plugins/cache/…) is codex-managed: surfaced as
 * advisory drift, never written, never affects inSync.
 */
async function converge(options: ConvergeCodexOptions, apply: boolean): Promise<ConvergeReport> {
  const pluginPath = join(homedir(), "plugins", PLUGIN_NAME);
  const manifestPath = join(pluginPath, ".codex-plugin", "plugin.json");
  const skillPath = join(pluginPath, "skills", PLUGIN_NAME, "SKILL.md");
  const marketplacePath = join(homedir(), ".agents", "plugins", "marketplace.json");

  const steps: ConvergeStep[] = [];
  steps.push({
    path: manifestPath,
    action: await convergeWrite(manifestPath, JSON.stringify(buildPluginManifest(options.version), null, 2) + "\n", apply),
  });
  steps.push({
    path: skillPath,
    action: await convergeWrite(skillPath, buildSkillSource(options.cliPath, options.version), apply),
  });
  steps.push({
    path: marketplacePath,
    action: await convergeMarketplace(marketplacePath, apply),
    note: "personal marketplace entry",
  });

  return {
    harness: "codex",
    mode: apply ? "apply" : "check",
    version: options.version,
    steps,
    drift: cacheDrift(options.version),
    inSync: computeInSync(steps),
  };
}

/**
 * Upsert planalot's entry in the shared personal marketplace, preserving every
 * other plugin and any unknown top-level fields. We authoritatively own only
 * the entry named PLUGIN_NAME.
 */
async function convergeMarketplace(path: string, apply: boolean): Promise<ConvergeAction> {
  const existed = existsSync(path);
  const marketplace = readMarketplace(path);
  marketplace.name ??= MARKETPLACE_NAME;
  marketplace.interface ??= { displayName: "Personal" };
  marketplace.interface.displayName ??= "Personal";
  marketplace.plugins ??= [];
  if (!Array.isArray(marketplace.plugins)) {
    throw new Error(`${path} field 'plugins' must be an array.`);
  }

  const entry = buildMarketplaceEntry();
  const index = marketplace.plugins.findIndex((candidate) => candidate?.name === PLUGIN_NAME);
  if (index >= 0) marketplace.plugins[index] = entry;
  else marketplace.plugins.push(entry);

  const desired = JSON.stringify(marketplace, null, 2) + "\n";
  if (existed && readFileSync(path, "utf8") === desired) return "unchanged";
  if (apply) {
    await mkdir(dirname(path), { recursive: true, mode: 0o700 });
    await writeFile(path, desired, "utf8");
  }
  return existed ? "updated" : "wrote";
}

/** Advisory drift for codex's own version-keyed cache, which the installer cannot write. */
function cacheDrift(localVersion: string): UnfixableDrift[] {
  const cacheRoot = join(homedir(), ".codex", "plugins", "cache", MARKETPLACE_NAME, PLUGIN_NAME);
  const reason = `codex runs from its own version-keyed cache; run \`codex plugin add ${PLUGIN_NAME}@${MARKETPLACE_NAME}\` or reload codex to refresh it`;
  const probes = readCacheProbes(cacheRoot, localVersion);
  if (probes.length === 0) {
    return [{ path: cacheRoot, reason: `cache not populated — ${reason}` }];
  }
  return probes.filter((probe) => !probe.matches).map((probe) => ({ path: probe.path, reason }));
}

function buildPluginManifest(version: string): unknown {
  return {
    name: PLUGIN_NAME,
    version,
    description: "Open local markdown plans in the Planalot browser review UI from Codex.",
    author: {
      name: "Local developer",
    },
    keywords: ["planalot", "planning", "feedback", "codex"],
    skills: "./skills/",
    interface: {
      displayName: "Planalot",
      shortDescription: "Open markdown plans in a local browser feedback UI.",
      longDescription:
        "Use Planalot from Codex to create or open markdown plans, start the local Planalot daemon, and review plans in a browser with annotations and feedback history.",
      developerName: "Local developer",
      category: "Productivity",
      capabilities: ["Interactive", "Read", "Write"],
      defaultPrompt: [
        "Open this plan in Planalot",
        "Create a plan and review it in Planalot",
        "Use Planalot for browser feedback on this task",
      ],
      brandColor: "#2563EB",
    },
  };
}

function buildSkillSource(cliPath: string, version: string): string {
  const command = shellCommandForCli(cliPath);
  return `---
name: planalot
description: Use when the user asks to create, continue, review, or implement a Planalot plan workspace from Codex.
planalot_version: ${version}
planalot_skill_revision: ${SKILL_REVISION}
---

# Planalot

${MARKER}. Re-run \`planalot install codex\` after updating or moving Planalot.

Installed Planalot version: \`${version}\`.

## Purpose

Planalot is a local second-brain planning workspace. It stores durable plans under \`~/.planalot/plans/<id>\`, with \`manifest.json\`, \`feedback.json\`, and plan-authored files under \`requirements/\`, \`design/\`, and \`tasks/\`. Use the CLI as the tool-like interface from Codex.

## Current Codex Harness Boundary

This integration is intentionally non-MCP. Codex interacts with Planalot by running CLI commands. To receive browser feedback and appear connected you **attach as a harness**; if your runtime can't keep a background process streaming, run \`attach\` in a separate terminal and paste the feedback lines, or poll with \`wait-feedback\`.

## Workflow — route on the request, then drive ONE plan

First decide intent: a markdown file path → **import**; "continue/resume <name>" → **find** then **read**; otherwise → **create**.

### 1. Create / import / continue

\`\`\`powershell
${command} create --name "Plan Name" --json
${command} import "PLAN.md" --name "Plan Name" --json
${command} find "payments" --status planning --json
${command} read <planId> --all --json
\`\`\`

Note the returned \`planId\`.

### 2. Attach as the harness (keep running)

Run this and keep it alive — in the background if your runtime supports it, otherwise in a separate terminal. It registers you with Planalot (the browser shows you connected) and streams feedback as one JSON object per line:

\`\`\`powershell
${command} attach <planId> --type codex --drive
\`\`\`

Planalot gives this instance a stable friendly name (e.g. \`amber-otter\`) shown in the browser's harness list and "Send to" dropdown, reused for this working directory across plans. Add \`--name "<name>"\` to choose your own.

If you cannot keep it running, poll instead: \`${command} wait-feedback <planId> --timeout 600 --json\`.

### 3. Author the plan, then open the browser

\`\`\`powershell
Get-Content -Raw updated-index.md | ${command} write <planId> requirements/index.md --stdin --json
${command} open <planId>
\`\`\`

Resolve top-down: \`requirements/\` → \`design/\` → \`tasks/\`.

### 4. Handle each feedback round

When a feedback event appears (in the \`attach\` stream, \`wait-feedback\` output, or chat): read files if needed, apply changes with \`write\` (you hold the exclusive edit lease for the round), then return the result:

\`\`\`powershell
Get-Content -Raw feedback-result.json | ${command} feedback-result <planId> --stdin --json
\`\`\`

### 5. Finish

\`\`\`powershell
${command} implement <planId> --json
${command} detach <planId>
\`\`\`

## Layered Plan Contract

Resolve top-down: \`requirements/\` -> \`design/\` -> \`tasks/\`.

- \`requirements/\`: goals, business rules, constraints, acceptance criteria, non-goals, open questions.
- \`design/\`: architecture, UX flows, data model, APIs, tradeoffs, risks, rejected alternatives.
- \`tasks/\`: implementation slices, dependencies, file ownership, verification commands, rollout notes.

If requirements change, reconcile design/tasks. If design changes, reconcile tasks. Do not silently change requirements because of downstream feedback; ask a question or explain the conflict.

## Feedback Result Protocol

Planalot sends feedback requests as markdown and expects only valid JSON back through \`feedback-result\`.

The result shape is:

\`\`\`json
{
  "schemaVersion": 1,
  "feedbackSessionId": "fs_...",
  "fileChanges": [
    {
      "path": "requirements/index.md",
      "operation": "updated",
      "feedbackItemIds": ["fb_..."],
      "content": "optional full file content",
      "alreadyApplied": false
    }
  ],
  "responses": [
    {
      "id": "r_...",
      "kind": "question",
      "feedbackItemIds": ["fb_..."],
      "layer": "requirements",
      "text": "Question, clarification, or insight.",
      "expectsUserFollowUp": true,
      "suggestedAnswers": []
    }
  ]
}
\`\`\`

## Constraints

- Planalot owns the source of truth once a plan is created or imported.
- Plan-authored files must be under \`requirements/\`, \`design/\`, or \`tasks/\`.
- \`requirements/index.md\` is required and canonical.
- Default discovery excludes expired plans; use \`--include-expired\` only when the user asks for old plans.
- Do not treat feedback as known until it appears in the \`attach\` stream, \`wait-feedback\` output, or chat.
- Keep \`attach\` running to appear connected; stop it with \`detach\` when finished. If nothing is attached, the browser shows "No harness connected" and sends fail.
- A feedback round is addressed to one harness, which holds an exclusive edit lease — the daemon rejects plan writes from anyone else with HTTP 409. Respond with \`feedback-result\` to release it.
`;
}

function readCacheProbes(cacheRoot: string, localVersion: string): CodexVersionProbe[] {
  if (!existsSync(cacheRoot)) return [];
  return readdirSync(cacheRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => readVersionProbe(join(cacheRoot, entry.name), localVersion));
}

function readVersionProbe(pluginPath: string, localVersion: string): CodexVersionProbe {
  const manifestPath = join(pluginPath, ".codex-plugin", "plugin.json");
  const skillPath = join(pluginPath, "skills", PLUGIN_NAME, "SKILL.md");
  const manifestVersion = readManifestVersion(manifestPath);
  const skillVersion = readSkillVersion(skillPath);
  const skillRevision = readSkillRevision(skillPath);
  const exists = existsSync(pluginPath);
  return {
    path: pluginPath,
    exists,
    ...(manifestVersion === undefined ? {} : { manifestVersion }),
    ...(skillVersion === undefined ? {} : { skillVersion }),
    ...(skillRevision === undefined ? {} : { skillRevision }),
    matches: exists && manifestVersion === localVersion && skillVersion === localVersion && skillRevision === SKILL_REVISION,
  };
}

function readMarketplace(path: string): Marketplace {
  if (!existsSync(path)) return { name: MARKETPLACE_NAME, interface: { displayName: "Personal" }, plugins: [] };
  const payload = JSON.parse(readFileSync(path, "utf8")) as Marketplace;
  if (typeof payload !== "object" || payload === null || Array.isArray(payload)) {
    throw new Error(`${path} must contain a JSON object.`);
  }
  return payload;
}

function buildMarketplaceEntry(): MarketplaceEntry {
  return {
    name: PLUGIN_NAME,
    source: {
      source: "local",
      path: `./plugins/${PLUGIN_NAME}`,
    },
    policy: {
      installation: "AVAILABLE",
      authentication: "ON_INSTALL",
    },
    category: "Productivity",
  };
}
